### ISSUE TITLE
axis_func.adjust_text() doesn't work with the legend from plots_2d.contourp()

### ISSUE THREAD

**Issue by MBravoS** [MBravoS/splotch#53] opened 2020-08-03 11:58 UTC
I noticed updating the examples notebook ([look at it for an example](https://github.com/MBravoS/splotch/blob/master/docs/Examples.ipynb)) that `axis_func.adjust_text()` can't find the legend generated by `plots_2d.contourp()`, raising a _No handles with labels found to put in legend._ warning. I suspect comes from how that legend is generated (which changed with the update that added filled contours), but I haven't figured out yet why it fails.

**Comment by AstroRobin** [comment] 2020-08-04 02:45
Fixed as of v0.5.1.1. Caused by issue with retrieving legend text objects.

**Closed** 2022-05-09 16:49 UTC
Labels: bug
